export  let books = [
    {
        "name": "Atomic Habits",
        "author": "James Clear",
        "genre": "Self-help",
        "page": 320,
        "published": 2018,
        "purchasedPrice": 20,
        "rentPrice": 3,
        "decription": "Atomic Habits is a guIde to making small changes that lead to remarkable results. It provides strategies for building good habits, breaking bad ones, and mastering the behaviors that lead to success.",
        "image": "../Assets/IMG/atomic_habit.jpg",
        "Id": 1
    },
    {
        "name": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "genre": "Classic",
        "page": 180,
        "published": 1925,
        "purchasedPrice": 15,
        "rentPrice": 2,
        "decription": "The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
        "image": "./Assets/IMG/the_greatest_gatsby.jpg",
        "Id": 2
    },
    {
        "name": "The Alchemist",
        "author": "Paulo Coelho",
        "genre": "Classic",
        "page": 200,
        "published": 1988,
        "purchasedPrice": 18,
        "rentPrice": 3,
        "decription": "The Alchemist follows the journey of an Andalusian shepherd  named Santiago. Believing a recurring dream to be prophetic, he asks a Romani fortune teller in a nearby town about its meaning"
        ,
        "image": "Assets/IMG/the_alchemist.jpg",
        "Id": 3
    },

    {
        "name":"The Power of Habit",
        "author": "Charles Duhigg",
        "genre": "Self-help",
        "page": 300,
        "published": 2012,
        "purchasedPrice": 22,
        "rentPrice": 4,
        "decription": "The Power of Habit is a book by Charles Duhigg, a New York Times reporter, published in February 2012 by Random House. It explores the science behind why habits exist and how they can be changed.",
        "image": "/Assets/IMG/the_power_of_habits.jpg",
        "Id": 4
    },

    {
        "name": "The Power of Now",
        "author": "Eckhart Tolle",
        "genre": "Spirituality",
        "page": 236,
        "published": 1997,
        "purchasedPrice": 20,
        "rentPrice": 3,
        "description": "The Power of Now is a guIde to spiritual enlightenment and living in the present moment. Eckhart Tolle shares how to overcome the mind's constraints to find true happiness.",
        "image": "/Assets/IMG/the_power_of_now.jpg",
        "Id": 5
    },
    {
        "name": "Daring Greatly",
        "author": "Brené Brown",
        "genre": "Self-help",
        "page": 304,
        "published": 2012,
        "purchasedPrice": 22,
        "rentPrice": 3,
        "description": "Daring Greatly explains how embracing vulnerability and imperfections can lead to a life of courage, connection, and purpose.",
        "image": "/Assets/IMG/darling_greatly.png",
        "Id": 6
    },
    {
        "name": "Rich Dad Poor Dad",
        "author": "Robert Kiyosaki",
        "genre": "Finance",
        "page": 336,
        "published": 1997,
        "purchasedPrice": 25,
        "rentPrice": 4,
        "description": "Rich Dad Poor Dad shares lessons on money management, investing, and building wealth based on the author's experiences with his two 'dads'—his biological father and his best friend's father.",
        "image": "/Assets/IMG/rich_dad_poor_dad.jpg",
        "Id": 7
    },
    {
        "name": "Start with Why",
        "author": "Simon Sinek",
        "genre": "Leadership",
        "page": 256,
        "published": 2009,
        "purchasedPrice": 23,
        "rentPrice": 3,
        "description": "Start with Why explores how great leaders inspire action by understanding their 'why' and communicating it effectively.",
        "image": "/Assets/IMG/start_with_why.jpg",
        "Id": 8
    },
    {
        "name": "Mindset: The New Psychology of Success",
        "author": "Carol S. Dweck",
        "genre": "Self-help",
        "page": 320,
        "published": 2006,
        "purchasedPrice": 24,
        "rentPrice": 3,
        "description": "Mindset explains the power of beliefs in shaping success, highlighting the differences between a fixed and growth mindset.",
        "image": "/Assets/IMG/mindset.jpg",
        "Id": 9
    },
    {
        "name": "Deep Work",
        "author": "Cal Newport",
        "genre": "Productivity",
        "page": 304,
        "published": 2016,
        "purchasedPrice": 26,
        "rentPrice": 4,
        "description": "Deep Work teaches strategies for focused success in a distracted world by cultivating deep work habits.",
        "image": "/Assets/IMG/deep_work.jpg",
        "Id": 10
    },
    {
        "name": "How to Win Friends and Influence People",
        "author": "Dale Carnegie",
        "genre": "Self-help",
        "page": 288,
        "published": 1936,
        "purchasedPrice": 21,
        "rentPrice": 3,
        "description": "This classic book provIdes timeless principles for building relationships, influencing people, and achieving personal and professional success.",
        "image": "/Assets/IMG/how_to_win_friends_and_influence_others.jpg",
        "Id": 11
    }, 

    {
        "name": "The 7 Habits of Highly Effective People",
        "autor": "Stephen R. Covey",
        "genre": "Self-help",
        "page": 250,
        "published": 1989,
        "purchasedPrice": 20,
        "rentPrice": 3,
        "decription": "The 7 Habits of Highly Effective People, first published in 1989, is a business and self-help book written by Stephen R. Covey. Covey presents an approach to being effective in attaining goals by aligning oneself to what he calls 'true north' principles based on a character ethic that he presents as universal and timeless.",
        "image": "/Assets/IMG/the_7_habits.jpg",
        "Id": 12
    },

    {
        "name": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "genre": "History",
        "page": 498,
        "published": 2011,
        "purchasedPrice": 28,
        "rentPrice": 5,
        "description": "Sapiens explores the history of humankind, from the emergence of Homo sapiens to the modern age, examining how biology and history have shaped our society.",
        "image": "/Assets/IMG/history_of_humankind.jpg",
        "Id": 13
    },
    {
        "name": "Educated",
        "author": "Tara Westover",
        "genre": "Memoir",
        "page": 352,
        "published": 2018,
        "purchasedPrice": 23,
        "rentPrice": 4,
        "description": "Educated is a memoir of a woman who grew up in a strict and abusive household in rural Idaho but eventually escapes to learn about the broader world through education.",
        "image": "/Assets/IMG/educated.jpg",
        "Id": 14
    },
    {
        "name": "The Four Agreements",
        "author": "Don Miguel Ruiz",
        "genre": "Self-help",
        "page": 160,
        "published": 1997,
        "purchasedPrice": 17,
        "rentPrice": 2,
        "description": "The Four Agreements offers a code of conduct based on ancient Toltec wisdom that can lead to personal freedom and happiness.",
        "image": "/Assets/IMG/the_four_agreements.jpg",
        "Id": 15
    },
    {
        "name": "Outliers: The Story of Success",
        "author": "Malcolm Gladwell",
        "genre": "Psychology",
        "page": 336,
        "published": 2008,
        "purchasedPrice": 24,
        "rentPrice": 4,
        "description": "Outliers examines the factors that contribute to high levels of success, focusing on the role of opportunity and cultural legacies.",
        "image": "/Assets/IMG/outliers.jpg",
        "Id": 16
    },
    {
        "name": "Can't Hurt Me",
        "author": "DavId Goggins",
        "genre": "Self-help",
        "page": 364,
        "published": 2018,
        "purchasedPrice": 30,
        "rentPrice": 5,
        "description": "Can't Hurt Me is a memoir of resilience and overcoming challenges, sharing lessons on mental toughness from Navy SEAL DavId Goggins.",
        "image": "/Assets/IMG/cant_hurt_me.jpg",
        "Id": 17
    },
    {
        "name": "The Lean Startup",
        "author": "Eric Ries",
        "genre": "Business",
        "page": 336,
        "published": 2011,
        "purchasedPrice": 27,
        "rentPrice": 4,
        "description": "The Lean Startup offers a methodology for developing businesses and products by building prototypes, testing, and iterating quickly.",
        "image": "/Assets/IMG/the_lean_startup.png",
        "Id": 18
    },
    {
        "name": "Think and Grow Rich",
        "author": "Napoleon Hill",
        "genre": "Self-help",
        "page": 238,
        "published": 1937,
        "purchasedPrice": 20,
        "rentPrice": 3,
        "description": "Think and Grow Rich explores the power of personal beliefs and the role they play in achieving success.",
        "image": "/Assets/IMG/think_and_grow_rich.jpg",
        "Id": 19
    },
    {
        "name": "The Art of War",
        "author": "Sun Tzu",
        "genre": "Philosophy",
        "page": 273,
        "published": -500,
        "purchasedPrice": 15,
        "rentPrice": 2,
        "description": "The Art of War is an ancient Chinese text on military strategy and tactics, offering wisdom applicable beyond the battlefield.",
        "image": "/Assets/IMG/the_art_of_war.jpg",
        "Id": 20
    },
    {
        "name": "Man's Search for Meaning",
        "author": "Viktor E. Frankl",
        "genre": "Psychology",
        "page": 200,
        "published": 1946,
        "purchasedPrice": 18,
        "rentPrice": 3,
        "description": "This book details Viktor Frankl's experiences in Nazi concentration camps and introduces his theory of logotherapy, centered on finding meaning in life.",
        "image": "/Assets/IMG/mans_search_for_meaning.jpg",
        "Id": 21
    },
    {
        "name": "The 5 Love Languages",
        "author": "Gary Chapman",
        "genre": "Relationships",
        "page": 208,
        "published": 1992,
        "purchasedPrice": 22,
        "rentPrice": 3,
        "description": "The 5 Love Languages explains how to improve relationships by understanding and responding to the different ways people express love.",
        "image": "/Assets/IMG/5_love_languages.jpg",
        "Id": 22
    },
    {
        "name": "Good to Great",
        "author": "Jim Collins",
        "genre": "Business",
        "page": 320,
        "published": 2001,
        "purchasedPrice": 25,
        "rentPrice": 4,
        "description": "Good to Great examines why some companies make the leap to greatness while others fail, offering insights from years of research.",
        "image": "/Assets/IMG/good_to_great.jpg",
        "Id": 23
    },
    {
        "name": "The War of Art",
        "author": "Steven Pressfield",
        "genre": "Creativity",
        "page": 165,
        "published": 2002,
        "purchasedPrice": 18,
        "rentPrice": 3,
        "description": "The War of Art addresses resistance, a universal force that prevents us from fulfilling our creative potential, and provIdes strategies to overcome it.",
        "image": "/Assets/IMG/the_war_of_art.jpg",
        "Id": 24
    },
    {
        "name": "Crushing It!",
        "author": "Gary Vaynerchuk",
        "genre": "Business",
        "page": 288,
        "published": 2018,
        "purchasedPrice": 26,
        "rentPrice": 4,
        "description": "Crushing It! shares stories of entrepreneurs who have leveraged social media to build thriving personal brands.",
        "image": "/Assets/IMG/crushing_it.jpg",
        "Id": 25
    },
    {
        "name": "Quiet: The Power of Introverts in a World That Can't Stop Talking",
        "author": "Susan Cain",
        "genre": "Psychology",
        "page": 352,
        "published": 2012,
        "purchasedPrice": 23,
        "rentPrice": 4,
        "description": "Quiet explores the unique strengths of introverts and how they can thrive in a society that often favors extroversion.",
        "image": "/Assets/IMG/quiet.png ",
        "Id": 26
    },
    {
        "name": "The Monk Who Sold His Ferrari",
        "author": "Robin Sharma",
        "genre": "Self-help",
        "page": 198,
        "published": 1997,
        "purchasedPrice": 20,
        "rentPrice": 3,
        "description": "This inspiring tale offers a step-by-step approach to living with greater courage, balance, abundance, and joy.",
        "image": "/Assets/IMG/the_monk_who_sold_his_ferrari.jpg",
        "Id": 27
    },
    {
        "name": "The Happiness Project",
        "author": "Gretchen Rubin",
        "genre": "Self-help",
        "page": 336,
        "published": 2009,
        "purchasedPrice": 24,
        "rentPrice": 4,
        "description": "The Happiness Project chronicles the author's year-long experiment to increase her own happiness and shares lessons learned.",
        "image": "/Assets/IMG/the_happiness_project.jpg",
        "Id": 28
    },
    {
        "name": "12 Rules for Life: An AntIdote to Chaos",
        "author": "Jordan B. Peterson",
        "genre": "Philosophy",
        "page": 448,
        "published": 2018,
        "purchasedPrice": 29,
        "rentPrice": 5,
        "description": "12 Rules for Life combines psychology, philosophy, and practical advice to guIde readers toward a meaningful life.",
        "image": "/Assets/IMG/12_rules_for_life.jpg",
        "Id": 29
    },
    {
        "name": "The Courage to Be Disliked",
        "author": "Ichiro Kishimi, Fumitake Koga",
        "genre": "Psychology",
        "page": 288,
        "published": 2013,
        "purchasedPrice": 22,
        "rentPrice": 3,
        "description": "This book explores Adlerian psychology and shows how we can free ourselves from the shackles of past traumas and social pressures.",
        "image": "/Assets/IMG/the_courage_to_be_disliked.jpg",
        "Id": 30
    },
    {
        "name": "The Secret",
        "author": "Rhonda Byrne",
        "genre": "Self-help",
        "page": 198,
        "published": 2006,
        "purchasedPrice": 19,
        "rentPrice": 3,
        "description": "The Secret reveals the law of attraction, offering guIdance on how to manifest positive outcomes in your life.",
        "image": "/Assets/IMG/the_secret.jpg",
        "Id": 31
    },
    {
        "name": "Grit: The Power of Passion and Perseverance",
        "author": "Angela Duckworth",
        "genre": "Psychology",
        "page": 352,
        "published": 2016,
        "purchasedPrice": 25,
        "rentPrice": 4,
        "description": "Grit examines how passion and perseverance drive success, based on research and real-life examples.",
        "image": "/Assets/IMG/grit.jpg",
        "Id": 32
    }

]

export let cart = [
    {
        "name": "The subtle art of not giving f**k",
        "autor": "mark manson",
        "genre": "classic",
        "page": 280,
        "published": 2015,
        "purchasedPrice": 25,
        "rentPrice": 4,
        "decription": "The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, the novel depicts narrator Nick Carraway's interactions with mysterious millionaire Jay Gatsby and Gatsby's obsession to reunite with his former lover, Daisy Buchanan.",
        "image": "/Assets/IMG/image.png",
        "Id": 1
    }

]